application: ob-demo
version: 2
runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app
# NO need for any additional URL handler rules:
# static files in {hive}/{sub}/client/pub/
# are served automatically via _go_app
